# Generated by Django 3.1.3 on 2020-11-24 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=260)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='books')),
                ('published_year', models.IntegerField(blank=True, null=True)),
                ('author', models.CharField(max_length=260)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='LibUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name='Full name')),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Up to 13 digits allowed.', regex='^\\d{13}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Library user',
                'verbose_name_plural': 'Library users',
            },
        ),
        migrations.CreateModel(
            name='PurchasedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Days count')),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book')),
                ('lib_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.libuser')),
            ],
            options={
                'verbose_name': 'Purchased Book',
                'verbose_name_plural': 'Purchased Books',
            },
        ),
    ]
